"""add venue time slot setup

Revision ID: 0643468ea00c
Revises: e26a54441c7e
Create Date: 2026-06-30 11:01:02.480709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0643468ea00c'
down_revision: Union[str, Sequence[str], None] = 'e26a54441c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'owner', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'venue_images', 'venues', ['venue_id'], ['id'])
    op.alter_column('venues', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_venues_type_lower'), table_name='venues')
    op.drop_index(op.f('venue_search_idx'), table_name='venues', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('venue_search_idx'), 'venues', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_venues_type_lower'), 'venues', [sa.literal_column('lower(type::text)')], unique=False)
    op.alter_column('venues', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'venue_images', type_='foreignkey')
    op.drop_constraint(None, 'owner', type_='foreignkey')
    # ### end Alembic commands ###
