"""add category to venues

Revision ID: 84c05b2e7549
Revises: fa79ba52b5c5
Create Date: 2026-06-15 12:36:11.771414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84c05b2e7549'
down_revision: Union[str, Sequence[str], None] = 'fa79ba52b5c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spatial_ref_sys')
    op.create_foreign_key(None, 'owner', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'venue_images', 'venues', ['venue_id'], ['id'])
    op.alter_column('venues', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('idx_venues_type_lower'), table_name='venues')
    op.drop_index(op.f('venue_search_idx'), table_name='venues', postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('venue_search_idx'), 'venues', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_venues_type_lower'), 'venues', [sa.literal_column('lower(type::text)')], unique=False)
    op.alter_column('venues', 'type',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(None, 'venue_images', type_='foreignkey')
    op.drop_constraint(None, 'owner', type_='foreignkey')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
